# Generated by Django 3.1.4 on 2021-01-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='PImage',
            field=models.ImageField(blank=True, null=True, upload_to='task/images'),
        ),
    ]
